a=5
print(type(a))
b=str("Hello World")
c=int(20)
d=float(20.5)
e=complex(1j)
f=list(("apple", "banana", "cherry"))
g=tuple(("apple", "banana", "cherry"))
h=range(6)
i=dict(name="John", age=36)
j=set(("apple", "banana", "cherry"))
k=frozenset(("apple", "banana", "cherry"))
l=bool(5)
m=bytes(5)
n=bytearray(5)
o=memoryview(bytes(5))