mytuple=("apple","banana","cherry")
print(mytuple)
thistuple=("apple","banana","cherry","apple","cherry")
print(thistuple)
print(len(thistuple))
histuple=("apple",)
print(type(histuple))

#NOT a tuple
histuple=("apple")
print(type(histuple))
tuple1=("apple","banana","cherry")
tuple2=(1,5,7,9,3)
tuple3=(True,False,False)
print(type(tuple1))
tuple4=("abc",34,True,40.6)
print(type(tuple4))
tuple5=tuple(("apple","banana","cherry"))
print(tuple5)